// <auto-generated />
using EmpoderamentoFemenino.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmpoderamentoFemenino.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("EmpoderamentoFemenino.Model.EmpoderamentoFeminino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Site")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Url")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("EmpoderamentoFeminino");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Django Girls é uma organização sem fins lucrativos e uma comunidade que capacita e ajuda mulheres a organizar oficinas de programação gratuitas de um dia, fornecendo ferramentas, recursos e suporte. Somos uma organização gerida por voluntários com centenas de pessoas contribuindo para trazer mais mulheres incríveis para o mundo da tecnologia. Estamos tornando a tecnologia mais acessível criando recursos projetados com empatia.Durante cada um dos nossos eventos, 30-60 mulheres constroem sua primeira aplicação web usando HTML, CSS, Python e Django.",
                            Nome = "Django Girls",
                            Site = "https://djangogirls.org/pt/",
                            Url = "https://www.youtube.com/watch?v=o0VZaM91DYI"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "O Minas Programam é uma iniciativa criada em 2015 para desafiar os estereótipos de gênero e de raça que influenciam nossa relação com as áreas de ciências, tecnologia e computação.Promovemos oportunidades de aprendizado sobre programação para meninas e mulheres, priorizando àquelas que são negras ou indígenas.",
                            Nome = "Minas Programam",
                            Site = "https://minasprogramam.com/",
                            Url = "https://www.youtube.com/channel/UCIXBQxnLSfGzNqG-AtsjDxQ"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "O PyLadies é uma comunidade mundial que foi trazida ao Brasil com o propósito de instigar mais mulheres a entrarem na área tecnológica. Queremos mudar essa realidade de poucas garotas em uma área tão rica e fantástica como a computação. E olhe que temos muita história nesse campo, viu?!",
                            Nome = "PyLadies",
                            Site = "http://brasil.pyladies.com/about/",
                            Url = "https://www.youtube.com/c/BrazilPyLadies"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "A {reprograma} é uma iniciativa de impacto social que foca em ensinar programação para mulheres cis e trans que não têm recursos e/ou oportunidades para aprender a programar.",
                            Nome = "Reprograma",
                            Site = "https://www.reprograma.com.br/",
                            Url = "https://www.youtube.com/c/reprogramabr"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Somos uma instituição sem fins lucrativos, com a missão de inspirar e impulsionar meninas e mulheres que desejam ingressar ou se especializar em carreiras ligadas à tecnologia e inovação (STEM).Desde 2015, lideramos uma série de iniciativas de capacitação, mentoria, empregabilidade e conteúdos digitais e alcançamos mais de 200 mil mulheres no Brasil, Chile e América do Norte.",
                            Nome = "WoMakersCode",
                            Site = "https://womakerscode.org/",
                            Url = "https://www.youtube.com/c/WoMakersCode"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
